version: '3.8'

services:
  blur_pipeline:
    image: blur_detection_app:latest
    container_name: blur_processor
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"

    environment:
      - DOCKER_INPUT_PATH=${DOCKER_INPUT_PATH}
      - DOCKER_OUTPUT_PATH=${DOCKER_OUTPUT_PATH}
      
    volumes:
      - "./blur_detection/assets:/workspace/blur_detection/blur_detection/assets"
      
      # DYNAMIC TRANSLATION VOLUMES (Using Long Syntax to prevent Drive Letter bugs)
      - type: bind
        source: ${DOCKER_INPUT_PATH}
        target: /data/input
      - type: bind
        source: ${DOCKER_OUTPUT_PATH}
        target: /data/output
      
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped