version: '3.8'

services:
  blur_pipeline:
    image: blur-detection-app
    container_name: blur_processor
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - "./blur_detection/assets:/workspace/blur_detection/blur_detection/assets"
      
      # DYNAMIC TRANSLATION VOLUMES
      - "${DOCKER_INPUT_PATH}:/data/input"
      - "${DOCKER_OUTPUT_PATH}:/data/output"
      
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped